name: figma_design_scale
description: Orientation-aware Figma-frame scaling for Flutter. Keeps layout and fonts stable across devices and rotations.
version: 0.1.1
repository: https://github.com/MNBLabs/figma_design_scale
issue_tracker: https://github.com/MNBLabs/figma_design_scale/issues
homepage: https://github.com/MNBLabs/figma_design_scale.git
topics: [responsive, layout, figma, scaling]

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
